apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: upravljanje-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: upravljanjeProfilov
    spec:
      containers:
      - image: tjasaj/upravljanje-profilov:0.03
        name: upravljanje-profilov
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP