apiVersion: v1
kind: Service
metadata:
  name: upravljanje-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32620
  selector:
    app: upravljanjeProfilov